title: "G-Wiki - Google Sheets Business Directory"
description: "A business directory wiki powered by Google Sheets and GitHub Pages"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # Change this to your GitHub Pages URL
repository: "yourusername/g-wiki" # Change this to your repository

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  businesses:
    output: true
    permalink: /business/:name/

# Google Sheets configuration
# NOTE: Do NOT put actual API keys here - use environment variables instead
google_sheets:
  spreadsheet_id: "1AhvzfKKUWTmApBQDCrMpwrY0iYhWzugyMepPucsvF3Y" # Replace with your Google Sheets ID
  # API key should be set as environment variable GOOGLE_API_KEY
  
# Site settings
timezone: America/New_York
encoding: utf-8
show_excerpts: false

# Navigation
header_pages:
  - index.md
  - categories.md
  - about.md

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - scripts/
