name: Sync Google Sheets Data

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  sync-data:
    runs-on: ubuntu-latest
    environment: main
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Check GitHub Context and Secrets
      run: |
        echo "=== GitHub Context Information ==="
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo ""
        echo "=== Available Secrets (checking if they exist) ==="
        echo "GOOGLE_SHEETS_ID secret exists: ${{ secrets.GOOGLE_SHEETS_ID != '' }}"
        echo "GOOGLE_API_KEY secret exists: ${{ secrets.GOOGLE_API_KEY != '' }}"
        echo ""
        echo "=== Environment Variables ==="
        env | grep -E "(GOOGLE|SHEET|API)" || echo "No GOOGLE/SHEET/API environment variables found"
        
    - name: Test secrets configuration
      env:
        GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        echo "=== Testing Direct Secret Access ==="
        echo "GOOGLE_SHEETS_ID from secret: '${{ secrets.GOOGLE_SHEETS_ID }}'"
        echo "GOOGLE_API_KEY from secret: '${{ secrets.GOOGLE_API_KEY }}'"
        echo ""
        echo "=== Testing Environment Variables ==="
        echo "GOOGLE_SHEETS_ID env var: '$GOOGLE_SHEETS_ID'"
        echo "GOOGLE_API_KEY env var: '$GOOGLE_API_KEY'"
        echo ""
        cd scripts
        python test_secrets.py
        
    - name: Debug environment variables
      env:
        GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        echo "Checking environment variables..."
        echo "GOOGLE_SHEETS_ID length: ${#GOOGLE_SHEETS_ID}"
        echo "GOOGLE_API_KEY length: ${#GOOGLE_API_KEY}"
        if [ -z "$GOOGLE_SHEETS_ID" ]; then
          echo "ERROR: GOOGLE_SHEETS_ID is empty or not set"
        else
          echo "GOOGLE_SHEETS_ID is set (length: ${#GOOGLE_SHEETS_ID})"
        fi
        if [ -z "$GOOGLE_API_KEY" ]; then
          echo "ERROR: GOOGLE_API_KEY is empty or not set"
        else
          echo "GOOGLE_API_KEY is set (length: ${#GOOGLE_API_KEY})"
        fi
        
    - name: Sync data from Google Sheets
      env:
        GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        cd scripts
        python sync_data.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Auto-sync data from Google Sheets"
        git push
